# Generated by Django 3.0 on 2020-12-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('TC', 'Tecnologia'), ('CR', 'Curiosidade'), ('GR', 'GERAL')], default='GR', max_length=2),
        ),
    ]
